//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMenu
    {
        public ApplicationMenu()
        {
            this.ApplicationPages = new HashSet<ApplicationPage>();
        }
    
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string MenuURL { get; set; }
        public Nullable<byte> MenuOrder { get; set; }
    
        public virtual ICollection<ApplicationPage> ApplicationPages { get; set; }
    }
}
