//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public County()
        {
            this.Districts = new HashSet<District>();
            this.JobRecordsOutOfOrganizations = new HashSet<JobRecordsOutOfOrganization>();
            this.MemberEducations = new HashSet<MemberEducation>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string Title { get; set; }
        public string LatinTitle { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<JobRecordsOutOfOrganization> JobRecordsOutOfOrganizations { get; set; }
        public virtual ICollection<MemberEducation> MemberEducations { get; set; }
    }
}
