//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string Title { get; set; }
        public string LatinTitle { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual County County { get; set; }
    }
}
