//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalField
    {
        public EducationalField()
        {
            this.MemberEducations = new HashSet<MemberEducation>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DepartmentOfEducationID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> RelatedField { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual DepartmentOfEducation DepartmentOfEducation { get; set; }
        public virtual ICollection<MemberEducation> MemberEducations { get; set; }
    }
}
