//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileExtension
    {
        public FileExtension()
        {
            this.Honors = new HashSet<Honor>();
            this.JobRecordsInOrganizations = new HashSet<JobRecordsInOrganization>();
            this.JobRecordsOutOfOrganizations = new HashSet<JobRecordsOutOfOrganization>();
            this.MemberEducations = new HashSet<MemberEducation>();
            this.PresentedArticles = new HashSet<PresentedArticle>();
            this.PublishedArticles = new HashSet<PublishedArticle>();
            this.SpecializedExperiences = new HashSet<SpecializedExperience>();
            this.Theses = new HashSet<Thesis>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsDownload { get; set; }
    
        public virtual ICollection<Honor> Honors { get; set; }
        public virtual ICollection<JobRecordsInOrganization> JobRecordsInOrganizations { get; set; }
        public virtual ICollection<JobRecordsOutOfOrganization> JobRecordsOutOfOrganizations { get; set; }
        public virtual ICollection<MemberEducation> MemberEducations { get; set; }
        public virtual ICollection<PresentedArticle> PresentedArticles { get; set; }
        public virtual ICollection<PublishedArticle> PublishedArticles { get; set; }
        public virtual ICollection<SpecializedExperience> SpecializedExperiences { get; set; }
        public virtual ICollection<Thesis> Theses { get; set; }
    }
}
