//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupControlForDelete
    {
        public int ID { get; set; }
        public string PrimaryTable { get; set; }
        public string ForeignTable { get; set; }
        public string ForeignField { get; set; }
    }
}
