//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShip
    {
        public MemberShip()
        {
            this.Honors = new HashSet<Honor>();
            this.JobRecordsInOrganizations = new HashSet<JobRecordsInOrganization>();
            this.JobRecordsOutOfOrganizations = new HashSet<JobRecordsOutOfOrganization>();
            this.MemberEducations = new HashSet<MemberEducation>();
            this.MemberResponsibilities = new HashSet<MemberResponsibility>();
            this.PresentedArticles = new HashSet<PresentedArticle>();
            this.PublishedArticles = new HashSet<PublishedArticle>();
            this.SpecializedExperiences = new HashSet<SpecializedExperience>();
            this.Theses = new HashSet<Thesis>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthOfDate { get; set; }
        public string NationalCode { get; set; }
        public string PersonnelCode { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string ConfirmationCode { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> FailedPasswordCount { get; set; }
        public Nullable<System.DateTime> AdminLockDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public byte[] ProfilePic { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<Honor> Honors { get; set; }
        public virtual ICollection<JobRecordsInOrganization> JobRecordsInOrganizations { get; set; }
        public virtual ICollection<JobRecordsOutOfOrganization> JobRecordsOutOfOrganizations { get; set; }
        public virtual ICollection<MemberEducation> MemberEducations { get; set; }
        public virtual ICollection<MemberResponsibility> MemberResponsibilities { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<PresentedArticle> PresentedArticles { get; set; }
        public virtual ICollection<PublishedArticle> PublishedArticles { get; set; }
        public virtual ICollection<SpecializedExperience> SpecializedExperiences { get; set; }
        public virtual ICollection<Thesis> Theses { get; set; }
    }
}
