//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagePatr
    {
        public PagePatr()
        {
            this.PagePartElements = new HashSet<PagePartElement>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ApplicationPageID { get; set; }
        public string PartDivID { get; set; }
        public string PartName { get; set; }
    
        public virtual ApplicationPage ApplicationPage { get; set; }
        public virtual ICollection<PagePartElement> PagePartElements { get; set; }
    }
}
