//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentedArticle
    {
        public int ID { get; set; }
        public Nullable<int> MemberShipID { get; set; }
        public string ConferenceTitle { get; set; }
        public string ArticlesTitle { get; set; }
        public Nullable<System.DateTime> PresentedDate { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<int> ExtensionID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual FileExtension FileExtension { get; set; }
        public virtual MemberShip MemberShip { get; set; }
    }
}
