//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Authorizations = new HashSet<Authorization>();
            this.MemberResponsibilities = new HashSet<MemberResponsibility>();
            this.MemberShips = new HashSet<MemberShip>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public string Title { get; set; }
        public Nullable<int> RoleLevelID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual ICollection<Authorization> Authorizations { get; set; }
        public virtual RoleLevel RoleLevel { get; set; }
        public virtual ICollection<MemberResponsibility> MemberResponsibilities { get; set; }
        public virtual ICollection<MemberShip> MemberShips { get; set; }
    }
}
