//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roshd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleLevel
    {
        public RoleLevel()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<byte> LevelOrder { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
